// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: services/wallet_service/proto/wallet.proto

package wallet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTotalBalanceByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalBalanceByUserIdRequest) Reset() {
	*x = GetTotalBalanceByUserIdRequest{}
	mi := &file_services_wallet_service_proto_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalBalanceByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalBalanceByUserIdRequest) ProtoMessage() {}

func (x *GetTotalBalanceByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_wallet_service_proto_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalBalanceByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetTotalBalanceByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_services_wallet_service_proto_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *GetTotalBalanceByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTotalBalanceByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalBalance  float64                `protobuf:"fixed64,2,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalBalanceByUserIdResponse) Reset() {
	*x = GetTotalBalanceByUserIdResponse{}
	mi := &file_services_wallet_service_proto_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalBalanceByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalBalanceByUserIdResponse) ProtoMessage() {}

func (x *GetTotalBalanceByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_wallet_service_proto_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalBalanceByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetTotalBalanceByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_services_wallet_service_proto_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *GetTotalBalanceByUserIdResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTotalBalanceByUserIdResponse) GetTotalBalance() float64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

var File_services_wallet_service_proto_wallet_proto protoreflect.FileDescriptor

const file_services_wallet_service_proto_wallet_proto_rawDesc = "" +
	"\n" +
	"*services/wallet_service/proto/wallet.proto\x12\x06wallet\"9\n" +
	"\x1eGetTotalBalanceByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"_\n" +
	"\x1fGetTotalBalanceByUserIdResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtotal_balance\x18\x02 \x01(\x01R\ftotalBalance2{\n" +
	"\rWalletService\x12j\n" +
	"\x17GetTotalBalanceByUserId\x12&.wallet.GetTotalBalanceByUserIdRequest\x1a'.wallet.GetTotalBalanceByUserIdResponseB\x16Z\x14pkg/pb/wallet;walletb\x06proto3"

var (
	file_services_wallet_service_proto_wallet_proto_rawDescOnce sync.Once
	file_services_wallet_service_proto_wallet_proto_rawDescData []byte
)

func file_services_wallet_service_proto_wallet_proto_rawDescGZIP() []byte {
	file_services_wallet_service_proto_wallet_proto_rawDescOnce.Do(func() {
		file_services_wallet_service_proto_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_wallet_service_proto_wallet_proto_rawDesc), len(file_services_wallet_service_proto_wallet_proto_rawDesc)))
	})
	return file_services_wallet_service_proto_wallet_proto_rawDescData
}

var file_services_wallet_service_proto_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_wallet_service_proto_wallet_proto_goTypes = []any{
	(*GetTotalBalanceByUserIdRequest)(nil),  // 0: wallet.GetTotalBalanceByUserIdRequest
	(*GetTotalBalanceByUserIdResponse)(nil), // 1: wallet.GetTotalBalanceByUserIdResponse
}
var file_services_wallet_service_proto_wallet_proto_depIdxs = []int32{
	0, // 0: wallet.WalletService.GetTotalBalanceByUserId:input_type -> wallet.GetTotalBalanceByUserIdRequest
	1, // 1: wallet.WalletService.GetTotalBalanceByUserId:output_type -> wallet.GetTotalBalanceByUserIdResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_wallet_service_proto_wallet_proto_init() }
func file_services_wallet_service_proto_wallet_proto_init() {
	if File_services_wallet_service_proto_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_wallet_service_proto_wallet_proto_rawDesc), len(file_services_wallet_service_proto_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_wallet_service_proto_wallet_proto_goTypes,
		DependencyIndexes: file_services_wallet_service_proto_wallet_proto_depIdxs,
		MessageInfos:      file_services_wallet_service_proto_wallet_proto_msgTypes,
	}.Build()
	File_services_wallet_service_proto_wallet_proto = out.File
	file_services_wallet_service_proto_wallet_proto_goTypes = nil
	file_services_wallet_service_proto_wallet_proto_depIdxs = nil
}
